
development:
  adapter: postgresql
  host: localhost
  database: sendhub_dev
  pool: 5
  timeout: 5000

  adapter: postgresql
  host: localhost
  database: sendhub_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: sendhub
  pool: 5
  timeout: 5000
